### ISSUE TITLE
PC Engine/TurboGrafx support non-functional

### ISSUE THREAD

**Issue by fluxcorenz** [fluxcorenz/UPCB#5]
The 'untested support' for PC Engine/TurboGrafx 16 has been tested - and shown to not work.

I'm currently in the process of rewriting the code. 

I have working support for 2 button mode, currently am working on a 6 button mode, and then will try 2 button autofire.

I will need to order a multitap to prove support for multiple controllers though, I have a feeling my current 2 button support will probably do strange things with the multitap.

**Comment by fluxcorenz** [comment]
I have preliminary support for 2 button and 6 button mode, but not 2 button autofire, and also am awaiting a multitap before being able to test correct behaviour in 2 player modes.

**Comment by RDCXBG** [comment]
Hey fluxcore, RDC from nfg here. Looks like those forums are down, so not sure if you received the last PM I sent there with the info on what SFII is doing for polling and how the Tap is really detected.

**Comment by fluxcorenz** [comment]
nfg being down is pretty crappy, I just linked someone to the 6-button controller schematic, only for them to say it doesn't work :(

Seems really odd that SF2 is doing 2x3byte polls, I suppose it must switch the SELECT line a bit faster to be able to fit in one extra byte (and a little bit longer for the extra ~OE toggle) in the end-to-end cycle? I quite like how much control a given game has over the controller polling on the PCE!

As for detection, you can plug the controllers into SF2 on the fly and have them detect 2 button vs 6 button and multitap, both on the main menu and the button options menu. Sometimes you need to SEL+RUN to exit back out of the main menu to have it detect properly though, so maybe that reset command also resets the controller detection? It's entirely possible this initial detection is too quick for me to control by the time all the various UPCB initialisation gets handled anyway, in which case I think the default outputs would be all HIGH, so it may just always have to get detected as a multitap. I don't think it's a big issue.

As for the turbo buttons, at the moment I'm thinking of just using the UPCB 'built in' turbo functionality (with the button held + program button + stick up or down to control speed), since it's already there. I've never used it myself, and I also need to confirm the PCE controller code will work when written in such a way to support it, but I think it's the most sensible way to go.

**Comment by RDCXBG** [comment]
Don't know what they did wrong, but that schematic works fine. I made one here on the breadboard from it. 

It's a 6us difference between the standard 5 byte poll (64us) and the 6 byte one (70us) that SFII is doing. 

NFG seems to be back online now, so I'll see you there.

**Comment by fluxcorenz** [comment]
Oh, I meant that the nfg site wasn't working, not that they even got to the point of being able to build the schematic :)

**Comment by RDCXBG** [comment]
Ah, gotcha.

**Comment by fluxcorenz** [comment]
Fixed as of release v2.9 :)
